import type { NavigationSection } from "@/navigation";
import {
	CommentDiscussionIcon,
	FlameIcon,
	GiftIcon,
	GoalIcon,
	ListUnorderedIcon,
	LogIcon,
	MegaphoneIcon,
	NoteIcon,
	PersonIcon,
	TasklistIcon,
	TelescopeIcon,
} from "@primer/octicons-react";

export const serviceNavigation: NavigationSection[] = [
	{
		id: "service",
		children: [
			{
				type: "item",
				id: "service.top",
				label: "Top Users",
				href: "/service/top",
				icon: <GoalIcon size={18} />,
				match: { mode: "segment-prefix" },
			},
			{
				type: "item",
				id: "service.announcements",
				label: "Announcements",
				href: "/service/announcements",
				icon: <MegaphoneIcon size={18} />,
				match: { mode: "segment-prefix" },
			},
			{
				type: "item",
				id: "service.events",
				label: "Events",
				href: "/service/events",
				icon: <TelescopeIcon size={18} />,
				match: { mode: "segment-prefix" },
			},
			{
				type: "item",
				id: "service.challenges",
				label: "Challenges",
				href: "/service/challenges",
				icon: <ListUnorderedIcon size={18} />,
				match: { mode: "segment-prefix" },
			},
			{
				type: "item",
				id: "service.challenge-sets",
				label: "Challenge Sets",
				href: "/service/challenge_sets",
				icon: <TasklistIcon size={18} />,
				match: { mode: "segment-prefix" },
			},
			{
				type: "item",
				id: "service.instances",
				label: "Instances",
				href: "/service/instances",
				icon: <FlameIcon size={18} />,
				match: { mode: "segment-prefix" },
			},
			{
				type: "item",
				id: "service.discussions",
				label: "Discussions",
				href: "/service/discussions",
				icon: <CommentDiscussionIcon size={18} />,
				match: { mode: "segment-prefix" },
			},
			{
				type: "item",
				id: "service.writeups",
				label: "Writeups",
				href: "/service/writeups",
				icon: <NoteIcon size={18} />,
				match: { mode: "segment-prefix" },
			},
			{
				type: "item",
				id: "service.solves",
				label: "Solves",
				href: "/service/solves",
				icon: <LogIcon size={18} />,
				match: { mode: "segment-prefix" },
			},
			{
				type: "item",
				id: "service.weapons",
				label: "Weapons",
				href: "/service/weapons",
				icon: <GiftIcon size={18} />,
				match: { mode: "segment-prefix" },
			},
			{
				type: "item",
				id: "service.profile",
				label: "Profile",
				href: "/service/profile",
				icon: <PersonIcon size={18} />,
				match: { mode: "segment-prefix" },
			},
		],
	},
];
