import type { AwdEventStatus, AwdPhase } from './sea_orm_active_enums';

export type AwdEvents = {
  id: string;
  event_id: string;
  status: AwdEventStatus;
  phase: AwdPhase;
  event_secret_ciphertext: string;
  event_secret_nonce: string;
  flagserver_token_ciphertext: string;
  flagserver_token_nonce: string;
  judgeserver_token_ciphertext: string;
  judgeserver_token_nonce: string;
  wg_server_private_key_ciphertext: string;
  wg_server_private_key_nonce: string;
  wg_server_public_key?: string;
  key_version: number;
  free_reset_count: number;
  extra_reset_penalty: number;
  reset_protection_secs: number;
  judge_max_concurrency: number;
  judge_default_timeout_secs: number;
  judge_retry_interval_secs: number;
  judge_grace_period_secs: number;
  round_duration_secs: number;
  archive_retention_hours: number;
  verified_at?: string;
  verified_revision?: string;
  pause_remaining_secs?: string;
  started_at?: string;
  finished_at?: string;
  created_at: string;
  updated_at: string;
  paused_phase?: AwdPhase;
  configuration_generation: number;
  verified_generation?: string;
};
