export type GameboxRevisions = {
  id: string;
  gamebox_id: string;
  version: string;
  revision_number: number;
  source_toml: string;
  spec_json: string;
  spec_digest: string;
  package_digest: string;
  image_ref?: string;
  image_id?: string;
  image_repo_digest?: string;
  username: string;
  recommended_cpu_millis: number;
  recommended_memory_bytes: number;
  recommended_pids_limit: number;
  healthchecks_json: string;
  judge_script_name?: string;
  judge_script_content?: string;
  judge_args_json?: string;
  judge_timeout_secs?: string;
  judge_retry_interval_secs?: string;
  build_status: string;
  build_error?: string;
  created_at: string;
};
