//! Complete HTTP route catalog for floatctf-api (mirrors service + admin config).

use super::{Auth, Method, NIL, Route};

fn p(template: &str) -> &'static str {
    Box::leak(template.replace("{id}", NIL).into_boxed_str())
}

/// Every service-side route under `/api`.
pub fn service_routes() -> Vec<Route> {
    vec![
        Route {
            method: Method::Post,
            path: "/api/users/session",
            auth: Auth::None,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: "/api/users",
            auth: Auth::None,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: "/api/users/reset_password",
            auth: Auth::None,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: "/api/users/reset?token=invalid",
            auth: Auth::None,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: "/api/users/me",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Patch,
            path: "/api/users/me",
            auth: Auth::UserRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: "/api/weapons",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/announcements",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/discussions",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/discussions/{id}"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/discussions",
            auth: Auth::UserRequired,
            json_body: true,
        },
        Route {
            method: Method::Patch,
            path: p("/api/discussions/{id}"),
            auth: Auth::UserRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: p("/api/discussions/{id}"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/discussions/{id}/like"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Delete,
            path: p("/api/discussions/{id}/like"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/discussions/{id}/comments"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/discussions/{id}/comments"),
            auth: Auth::UserRequired,
            json_body: true,
        },
        Route {
            method: Method::Patch,
            path: p("/api/discussions/{id}/comments/{id}"),
            auth: Auth::UserRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: p("/api/discussions/{id}/comments/{id}"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/uploads/image",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Patch,
            path: "/api/uploads/avatar",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/submit/flag",
            auth: Auth::UserRequired,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: "/api/submit/writeup",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/writeups/{id}"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/writeups",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/challenges",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/challenges/{id}"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/challenges/{id}/instance"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/challenges/{id}/my_writeup"),
            auth: Auth::UserRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: p("/api/challenges/{id}/my_writeup"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/challenges/{id}/writeups"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/challenge_sets",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/challenge_sets/{id}"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/instances",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/instances/{id}"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/instances/launch",
            auth: Auth::UserRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: p("/api/instances/{id}"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/solves",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/solves/top15users",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/events",
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/challenges"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/instances"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/challenges/{id}/instance"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/scoreboard"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/announcements"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/trend"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/own_wp"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/events/{id}/join"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Delete,
            path: p("/api/events/{id}/leave"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/events/{id}/team"),
            auth: Auth::UserRequired,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: p("/api/events/{id}/team/{id}/join"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Delete,
            path: p("/api/events/{id}/team/{id}"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        // ── AWD 选手端（/api/events/{event_id}/awd/...）──
        // 这 8 条此前完全不在目录里，所以 get_scores 漏守卫时契约测试抓不到。
        // 只登记 /events 前缀：顶层 /api 的重复注册已移除（否则每条都有第二份可达路径）。
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/awd/gameboxes"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/events/{id}/awd/gameboxes/{id}/reset"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/events/{id}/awd/submissions"),
            auth: Auth::UserRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/awd/ssh-config"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/awd/scores"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/awd/wireguard/config"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/awd/status"),
            auth: Auth::UserRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/events/{id}/awd/stream"),
            auth: Auth::UserRequired,
            json_body: false,
        },
    ]
}

pub fn admin_routes() -> Vec<Route> {
    vec![
        Route {
            method: Method::Post,
            path: "/api/admin/session",
            auth: Auth::None,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/download?key=x",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/system/monitor",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/system/version",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/database/exec_sql",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/announcements",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/announcements",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: "/api/admin/announcements",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Patch,
            path: p("/api/admin/announcements/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/discussions",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/discussions/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Delete,
            path: "/api/admin/discussions",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/discussions/{id}/comments"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Delete,
            path: p("/api/admin/discussions/{id}/comments/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/settings",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/settings",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: "/api/admin/settings",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Patch,
            path: p("/api/admin/settings/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/weapons",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/weapons",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: "/api/admin/weapons",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Patch,
            path: p("/api/admin/weapons/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/weapons/{id}/upload"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/users",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/users/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/users",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: "/api/admin/users",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Patch,
            path: p("/api/admin/users/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/challenges",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/challenges/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/challenges",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/challenges/check",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/challenges/import",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/challenges/build",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: "/api/admin/challenges",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Patch,
            path: p("/api/admin/challenges/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/challenge_sets",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/challenge_sets/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/challenge_sets",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: "/api/admin/challenge_sets",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Patch,
            path: p("/api/admin/challenge_sets/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/challenge_sets/{id}/challenges"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: p("/api/admin/challenge_sets/{id}/challenges"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/super_admin",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/super_admin/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/super_admin",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: "/api/admin/super_admin",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/super_admin/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/events/{id}/instances"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/events",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/events/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/events",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: "/api/admin/events",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Patch,
            path: p("/api/admin/events/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/events/{id}/data"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/events/{id}/report"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/events/{id}/users"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/events/{id}/users"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: p("/api/admin/events/{id}/users"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/events/{id}/users/{id}/banned"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/events/{id}/users/{id}/unbanned"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/events/{id}/teams"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/events/{id}/teams"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: p("/api/admin/events/{id}/teams"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/events/{id}/teams/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/events/{id}/teams/{id}/users"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: p("/api/admin/events/{id}/teams/{id}/users"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/events/{id}/teams/{id}/banned"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/events/{id}/teams/{id}/unbanned"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/events/{id}/challenges"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/events/{id}/challenges"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: p("/api/admin/events/{id}/challenges"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/events/{id}/challenges/hidden"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/events/{id}/challenges/open"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/events/{id}/announcements"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/events/{id}/announcements/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/events/{id}/announcements"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Patch,
            path: p("/api/admin/events/{id}/announcements/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: p("/api/admin/events/{id}/announcements"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/events/{id}/writeups"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/events/{id}/logs"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/scheduled_tasks",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/scheduled_tasks/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/scheduled_tasks",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/scheduled_tasks/{id}/run"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Delete,
            path: "/api/admin/scheduled_tasks",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Patch,
            path: p("/api/admin/scheduled_tasks/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/logs",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: p("/api/admin/logs/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/docker/containers",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/docker/containers/{id}/stop"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: p("/api/admin/docker/containers/{id}/start"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Delete,
            path: p("/api/admin/docker/containers/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/docker/images",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Delete,
            path: p("/api/admin/docker/images/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Get,
            path: "/api/admin/docker/networks",
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
        Route {
            method: Method::Post,
            path: "/api/admin/docker/networks",
            auth: Auth::SuperAdminRequired,
            json_body: true,
        },
        Route {
            method: Method::Delete,
            path: p("/api/admin/docker/networks/{id}"),
            auth: Auth::SuperAdminRequired,
            json_body: false,
        },
    ]
}
