//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::AwdEventStatus;
use super::sea_orm_active_enums::AwdPhase;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub event_id: Uuid,
    pub status: AwdEventStatus,
    pub phase: AwdPhase,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub event_secret_ciphertext: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub event_secret_nonce: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub flagserver_token_ciphertext: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub flagserver_token_nonce: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub judgeserver_token_ciphertext: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub judgeserver_token_nonce: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub wg_server_private_key_ciphertext: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub wg_server_private_key_nonce: Option<Vec<u8>>,
    pub wg_server_public_key: Option<String>,
    pub key_version: i32,
    pub free_reset_count: i32,
    pub extra_reset_penalty: i64,
    pub judge_max_concurrency: i32,
    pub judge_default_timeout_secs: i32,
    pub judge_retry_interval_secs: i32,
    pub judge_grace_period_secs: i32,
    pub round_duration_secs: i32,
    pub archive_retention_hours: i32,
    pub verified_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub verified_revision: Option<String>,
    pub pause_remaining_secs: Option<i32>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub paused_phase: Option<AwdPhase>,
    pub configuration_generation: i64,
    pub verified_generation: Option<i64>,
    pub round_count: Option<i32>,
    pub initial_score: i64,
    pub hardening_ends_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awd_event_gameboxes::Entity")]
    AwdEventGameboxes,
    #[sea_orm(has_one = "super::awd_event_networks::Entity")]
    AwdEventNetworks,
    #[sea_orm(has_many = "super::awd_flag_issues::Entity")]
    AwdFlagIssues,
    #[sea_orm(has_many = "super::awd_flag_submissions::Entity")]
    AwdFlagSubmissions,
    #[sea_orm(has_many = "super::awd_internal_token_rotations::Entity")]
    AwdInternalTokenRotations,
    #[sea_orm(has_many = "super::awd_judge_batches::Entity")]
    AwdJudgeBatches,
    #[sea_orm(has_many = "super::awd_judge_tasks::Entity")]
    AwdJudgeTasks,
    #[sea_orm(has_many = "super::awd_orphan_resources::Entity")]
    AwdOrphanResources,
    #[sea_orm(has_many = "super::awd_precheck_runs::Entity")]
    AwdPrecheckRuns,
    #[sea_orm(has_many = "super::awd_reset_records::Entity")]
    AwdResetRecords,
    #[sea_orm(has_many = "super::awd_rounds::Entity")]
    AwdRounds,
    #[sea_orm(has_many = "super::awd_runtime_resources::Entity")]
    AwdRuntimeResources,
    #[sea_orm(has_many = "super::awd_score_events::Entity")]
    AwdScoreEvents,
    #[sea_orm(has_many = "super::awd_team_bans::Entity")]
    AwdTeamBans,
    #[sea_orm(has_many = "super::awd_team_networks::Entity")]
    AwdTeamNetworks,
    #[sea_orm(has_many = "super::awd_wireguard_peers::Entity")]
    AwdWireguardPeers,
    #[sea_orm(has_many = "super::event_gamebox_instances::Entity")]
    EventGameboxInstances,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::awd_event_gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEventGameboxes.def()
    }
}

impl Related<super::awd_event_networks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEventNetworks.def()
    }
}

impl Related<super::awd_flag_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagIssues.def()
    }
}

impl Related<super::awd_flag_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagSubmissions.def()
    }
}

impl Related<super::awd_internal_token_rotations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdInternalTokenRotations.def()
    }
}

impl Related<super::awd_judge_batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdJudgeBatches.def()
    }
}

impl Related<super::awd_judge_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdJudgeTasks.def()
    }
}

impl Related<super::awd_orphan_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdOrphanResources.def()
    }
}

impl Related<super::awd_precheck_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdPrecheckRuns.def()
    }
}

impl Related<super::awd_reset_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdResetRecords.def()
    }
}

impl Related<super::awd_rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdRounds.def()
    }
}

impl Related<super::awd_runtime_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdRuntimeResources.def()
    }
}

impl Related<super::awd_score_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdScoreEvents.def()
    }
}

impl Related<super::awd_team_bans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdTeamBans.def()
    }
}

impl Related<super::awd_team_networks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdTeamNetworks.def()
    }
}

impl Related<super::awd_wireguard_peers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdWireguardPeers.def()
    }
}

impl Related<super::event_gamebox_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventGameboxInstances.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
