//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_runtime_resources")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub resource_type: String,
    pub resource_id: String,
    pub resource_name: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub observed_state: Option<Json>,
    pub last_seen_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awd_events::Entity",
        from = "Column::EventId",
        to = "super::awd_events::Column::EventId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdEvents,
}

impl Related<super::awd_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEvents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
