//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::JudgeTaskStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_judge_tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub batch_id: Uuid,
    pub event_id: Uuid,
    pub round_id: Uuid,
    pub gamebox_instance_id: Uuid,
    pub team_id: Uuid,
    pub status: JudgeTaskStatus,
    pub attempt_count: i32,
    pub max_attempts: i32,
    pub deadline_at: DateTimeWithTimeZone,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub exit_code: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stdout_limited: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stderr_limited: Option<String>,
    pub duration_ms: Option<i32>,
    pub callback_idempotency_key: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub event_gamebox_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awd_event_gameboxes::Entity",
        from = "Column::EventGameboxId",
        to = "super::awd_event_gameboxes::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AwdEventGameboxes,
    #[sea_orm(
        belongs_to = "super::awd_events::Entity",
        from = "Column::EventId",
        to = "super::awd_events::Column::EventId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdEvents,
    #[sea_orm(
        belongs_to = "super::awd_judge_batches::Entity",
        from = "Column::BatchId",
        to = "super::awd_judge_batches::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdJudgeBatches,
    #[sea_orm(
        belongs_to = "super::awd_rounds::Entity",
        from = "Column::RoundId",
        to = "super::awd_rounds::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdRounds,
    #[sea_orm(
        belongs_to = "super::event_gamebox_instances::Entity",
        from = "Column::GameboxInstanceId",
        to = "super::event_gamebox_instances::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventGameboxInstances,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "Column::TeamId",
        to = "super::event_teams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams,
}

impl Related<super::awd_event_gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEventGameboxes.def()
    }
}

impl Related<super::awd_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEvents.def()
    }
}

impl Related<super::awd_judge_batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdJudgeBatches.def()
    }
}

impl Related<super::awd_rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdRounds.def()
    }
}

impl Related<super::event_gamebox_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventGameboxInstances.def()
    }
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
