//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::BanStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_team_bans")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub team_id: Uuid,
    pub status: BanStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    pub effective_round_id: Option<Uuid>,
    pub banned_by: Option<Uuid>,
    pub banned_at: DateTimeWithTimeZone,
    pub unban_requested_at: Option<DateTimeWithTimeZone>,
    pub unban_effective_round_id: Option<Uuid>,
    pub unbanned_by: Option<Uuid>,
    pub unbanned_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awd_rounds::Entity",
        from = "Column::EffectiveRoundId",
        to = "super::awd_rounds::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AwdRounds2,
    #[sea_orm(
        belongs_to = "super::awd_rounds::Entity",
        from = "Column::UnbanEffectiveRoundId",
        to = "super::awd_rounds::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AwdRounds1,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "Column::TeamId",
        to = "super::event_teams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
    #[sea_orm(
        belongs_to = "super::super_admin::Entity",
        from = "Column::BannedBy",
        to = "super::super_admin::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SuperAdmin2,
    #[sea_orm(
        belongs_to = "super::super_admin::Entity",
        from = "Column::UnbannedBy",
        to = "super::super_admin::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SuperAdmin1,
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
