//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_flag_submissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub round_id: Uuid,
    pub flag_issue_id: Uuid,
    pub attacker_team_id: Uuid,
    pub victim_team_id: Uuid,
    pub gamebox_instance_id: Uuid,
    pub submitted_by_user_id: Uuid,
    pub submitted_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awd_flag_issues::Entity",
        from = "Column::FlagIssueId",
        to = "super::awd_flag_issues::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdFlagIssues,
    #[sea_orm(
        belongs_to = "super::awd_gamebox_instances::Entity",
        from = "Column::GameboxInstanceId",
        to = "super::awd_gamebox_instances::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdGameboxInstances,
    #[sea_orm(
        belongs_to = "super::awd_rounds::Entity",
        from = "Column::RoundId",
        to = "super::awd_rounds::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdRounds,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "Column::AttackerTeamId",
        to = "super::event_teams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams2,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "Column::VictimTeamId",
        to = "super::event_teams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams1,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::SubmittedByUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::awd_flag_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagIssues.def()
    }
}

impl Related<super::awd_gamebox_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdGameboxInstances.def()
    }
}

impl Related<super::awd_rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdRounds.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
