//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::GameboxStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_gamebox_instances")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub team_id: Uuid,
    pub status: GameboxStatus,
    #[sea_orm(unique)]
    pub container_name: String,
    #[sea_orm(column_type = "custom(\"inet\")")]
    pub gamebox_ip: String,
    pub health_status: String,
    pub reset_protection_until: Option<DateTimeWithTimeZone>,
    pub last_health_check_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub event_gamebox_id: Uuid,
    pub runtime_generation: i64,
    pub current_container_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awd_event_gameboxes::Entity",
        from = "Column::EventGameboxId",
        to = "super::awd_event_gameboxes::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    AwdEventGameboxes,
    #[sea_orm(has_many = "super::awd_flag_issues::Entity")]
    AwdFlagIssues,
    #[sea_orm(has_many = "super::awd_flag_submissions::Entity")]
    AwdFlagSubmissions,
    #[sea_orm(has_many = "super::awd_judge_tasks::Entity")]
    AwdJudgeTasks,
    #[sea_orm(has_many = "super::awd_reset_records::Entity")]
    AwdResetRecords,
    #[sea_orm(has_many = "super::awd_score_events::Entity")]
    AwdScoreEvents,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "Column::TeamId",
        to = "super::event_teams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::awd_event_gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEventGameboxes.def()
    }
}

impl Related<super::awd_flag_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagIssues.def()
    }
}

impl Related<super::awd_flag_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagSubmissions.def()
    }
}

impl Related<super::awd_judge_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdJudgeTasks.def()
    }
}

impl Related<super::awd_reset_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdResetRecords.def()
    }
}

impl Related<super::awd_score_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdScoreEvents.def()
    }
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
