//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::GameboxStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_gamebox_instances")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "awd_gamebox_instances_event_id_template_id_team_id_key")]
    pub event_id: Uuid,
    #[sea_orm(unique_key = "awd_gamebox_instances_event_id_template_id_team_id_key")]
    pub template_id: Uuid,
    #[sea_orm(unique_key = "awd_gamebox_instances_event_id_template_id_team_id_key")]
    pub team_id: Uuid,
    pub status: GameboxStatus,
    pub container_id: Option<String>,
    #[sea_orm(unique)]
    pub container_name: String,
    #[sea_orm(unique_key = "awd_gamebox_instances_event_id_gamebox_ip_key")]
    pub gamebox_ip: String,
    pub docker_network_id: Option<String>,
    pub health_status: String,
    pub reset_protection_until: Option<DateTimeWithTimeZone>,
    pub last_health_check_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awd_flag_issues::Entity")]
    AwdFlagIssues,
    #[sea_orm(has_many = "super::awd_flag_submissions::Entity")]
    AwdFlagSubmissions,
    #[sea_orm(
        belongs_to = "super::awd_gamebox_templates::Entity",
        from = "Column::TemplateId",
        to = "super::awd_gamebox_templates::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdGameboxTemplates,
    #[sea_orm(has_many = "super::awd_judge_tasks::Entity")]
    AwdJudgeTasks,
    #[sea_orm(has_many = "super::awd_reset_records::Entity")]
    AwdResetRecords,
    #[sea_orm(has_many = "super::awd_score_events::Entity")]
    AwdScoreEvents,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "Column::TeamId",
        to = "super::event_teams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::awd_flag_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagIssues.def()
    }
}

impl Related<super::awd_flag_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagSubmissions.def()
    }
}

impl Related<super::awd_gamebox_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdGameboxTemplates.def()
    }
}

impl Related<super::awd_judge_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdJudgeTasks.def()
    }
}

impl Related<super::awd_reset_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdResetRecords.def()
    }
}

impl Related<super::awd_score_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdScoreEvents.def()
    }
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
