//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::PrecheckStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_precheck_runs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub status: PrecheckStatus,
    pub trigger: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub revision: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub config_check: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub container_check: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub wireguard_check: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub network_check: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub flag_check: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub judge_check: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_msg: Option<String>,
    pub started_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
