//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::ScoreEventType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_score_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub round_id: Option<Uuid>,
    pub team_id: Uuid,
    pub event_type: ScoreEventType,
    pub delta: i64,
    #[sea_orm(unique)]
    pub idempotency_key: String,
    pub related_team_id: Option<Uuid>,
    pub gamebox_instance_id: Option<Uuid>,
    pub reference_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata_json: Json,
    pub created_by: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub event_gamebox_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awd_event_gameboxes::Entity",
        from = "Column::EventGameboxId",
        to = "super::awd_event_gameboxes::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AwdEventGameboxes,
    #[sea_orm(
        belongs_to = "super::awd_events::Entity",
        from = "Column::EventId",
        to = "super::awd_events::Column::EventId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdEvents,
    #[sea_orm(
        belongs_to = "super::awd_gamebox_instances::Entity",
        from = "Column::GameboxInstanceId",
        to = "super::awd_gamebox_instances::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AwdGameboxInstances,
    #[sea_orm(
        belongs_to = "super::awd_rounds::Entity",
        from = "Column::RoundId",
        to = "super::awd_rounds::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AwdRounds,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "Column::RelatedTeamId",
        to = "super::event_teams::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    EventTeams2,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "Column::TeamId",
        to = "super::event_teams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams1,
    #[sea_orm(
        belongs_to = "super::super_admin::Entity",
        from = "Column::CreatedBy",
        to = "super::super_admin::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SuperAdmin,
}

impl Related<super::awd_event_gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEventGameboxes.def()
    }
}

impl Related<super::awd_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEvents.def()
    }
}

impl Related<super::awd_gamebox_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdGameboxInstances.def()
    }
}

impl Related<super::awd_rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdRounds.def()
    }
}

impl Related<super::super_admin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SuperAdmin.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
