//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_reset_records")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub team_id: Uuid,
    pub gamebox_instance_id: Uuid,
    pub round_id: Option<Uuid>,
    pub requested_by: Option<Uuid>,
    pub free_reset: bool,
    pub penalty_score_event_id: Option<Uuid>,
    pub status: String,
    pub started_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_msg: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awd_gamebox_instances::Entity",
        from = "Column::GameboxInstanceId",
        to = "super::awd_gamebox_instances::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdGameboxInstances,
    #[sea_orm(
        belongs_to = "super::awd_rounds::Entity",
        from = "Column::RoundId",
        to = "super::awd_rounds::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AwdRounds,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "Column::TeamId",
        to = "super::event_teams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::RequestedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::awd_gamebox_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdGameboxInstances.def()
    }
}

impl Related<super::awd_rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdRounds.def()
    }
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
