//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use ipnetwork::IpNetwork;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_network_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i16,
    #[sea_orm(column_type = "custom(\"cidr\")")]
    pub gamebox_pool: IpNetwork,
    pub gamebox_event_prefix: i16,
    pub gamebox_team_prefix: i16,
    #[sea_orm(column_type = "custom(\"cidr\")")]
    pub wireguard_pool: IpNetwork,
    pub wireguard_event_prefix: i16,
    pub wireguard_team_prefix: i16,
    pub wireguard_port_min: i32,
    pub wireguard_port_max: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub wireguard_public_endpoint: Option<String>,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
