//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_gamebox_templates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "awd_gamebox_templates_event_id_name_key")]
    pub event_id: Uuid,
    pub challenge_id: Option<Uuid>,
    #[sea_orm(unique_key = "awd_gamebox_templates_event_id_name_key")]
    pub name: String,
    pub image_ref: String,
    pub username: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub meta_json: Json,
    pub cpu_millis: i64,
    pub memory_bytes: i64,
    pub pids_limit: i64,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub healthcheck_override_json: Option<Json>,
    pub judge_script_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub judge_script_content: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub judge_args_json: Option<Json>,
    pub judge_timeout_secs: Option<i32>,
    pub judge_retry_interval_secs: Option<i32>,
    pub break_points: i64,
    pub loss_points: i64,
    pub fix_points: i64,
    pub down_points: i64,
    pub first_bonus: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awd_gamebox_instances::Entity")]
    AwdGameboxInstances,
    #[sea_orm(has_many = "super::awd_judge_tasks::Entity")]
    AwdJudgeTasks,
    #[sea_orm(has_many = "super::awd_score_events::Entity")]
    AwdScoreEvents,
    #[sea_orm(
        belongs_to = "super::challenges::Entity",
        from = "Column::ChallengeId",
        to = "super::challenges::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Challenges,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::awd_gamebox_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdGameboxInstances.def()
    }
}

impl Related<super::awd_judge_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdJudgeTasks.def()
    }
}

impl Related<super::awd_score_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdScoreEvents.def()
    }
}

impl Related<super::challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenges.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
