//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::AwdNetworkAllocationMode;
use ipnetwork::IpNetwork;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_event_networks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub event_id: Uuid,
    pub allocation_mode: AwdNetworkAllocationMode,
    #[sea_orm(column_type = "custom(\"cidr\")")]
    pub gamebox_cidr: IpNetwork,
    #[sea_orm(column_type = "custom(\"cidr\")")]
    pub wireguard_cidr: IpNetwork,
    #[sea_orm(column_type = "custom(\"cidr\")")]
    pub infrastructure_subnet: IpNetwork,
    #[sea_orm(column_type = "custom(\"inet\")")]
    pub flagserver_ip: IpNetwork,
    #[sea_orm(column_type = "custom(\"inet\")")]
    pub judgeserver_ip: IpNetwork,
    #[sea_orm(unique)]
    pub wireguard_interface_name: String,
    #[sea_orm(unique)]
    pub wireguard_listen_port: i32,
    #[sea_orm(unique)]
    pub docker_network_name: String,
    pub locked_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
