//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_internal_token_rotations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub token_type: String,
    pub rotated_by: Option<Uuid>,
    pub rotated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awd_events::Entity",
        from = "Column::EventId",
        to = "super::awd_events::Column::EventId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdEvents,
    #[sea_orm(
        belongs_to = "super::super_admin::Entity",
        from = "Column::RotatedBy",
        to = "super::super_admin::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SuperAdmin,
}

impl Related<super::awd_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEvents.def()
    }
}

impl Related<super::super_admin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SuperAdmin.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
