//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::AwdPhase;
use super::sea_orm_active_enums::RoundStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_rounds")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "idx_awd_rounds_one_active")]
    pub event_id: Uuid,
    #[sea_orm(unique_key = "awd_rounds_event_id_round_number_key")]
    pub round_number: i32,
    #[sea_orm(unique_key = "idx_awd_rounds_one_active")]
    pub status: RoundStatus,
    pub phase: AwdPhase,
    pub started_at: DateTimeWithTimeZone,
    pub scheduled_end_at: DateTimeWithTimeZone,
    pub grace_ends_at: Option<DateTimeWithTimeZone>,
    pub paused_at: Option<DateTimeWithTimeZone>,
    pub remaining_secs: Option<i32>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awd_flag_issues::Entity")]
    AwdFlagIssues,
    #[sea_orm(has_many = "super::awd_flag_submissions::Entity")]
    AwdFlagSubmissions,
    #[sea_orm(has_many = "super::awd_judge_batches::Entity")]
    AwdJudgeBatches,
    #[sea_orm(has_many = "super::awd_judge_tasks::Entity")]
    AwdJudgeTasks,
    #[sea_orm(has_many = "super::awd_reset_records::Entity")]
    AwdResetRecords,
    #[sea_orm(has_many = "super::awd_score_events::Entity")]
    AwdScoreEvents,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::awd_flag_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagIssues.def()
    }
}

impl Related<super::awd_flag_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagSubmissions.def()
    }
}

impl Related<super::awd_judge_batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdJudgeBatches.def()
    }
}

impl Related<super::awd_judge_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdJudgeTasks.def()
    }
}

impl Related<super::awd_reset_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdResetRecords.def()
    }
}

impl Related<super::awd_score_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdScoreEvents.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
