//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::AwdEventStatus;
use super::sea_orm_active_enums::AwdPhase;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub event_id: Uuid,
    pub status: AwdEventStatus,
    pub phase: AwdPhase,
    pub gamebox_cidr: String,
    pub wireguard_cidr: String,
    #[sea_orm(unique)]
    pub wireguard_interface_name: String,
    #[sea_orm(unique)]
    pub wireguard_listen_port: i32,
    pub flagserver_ip: String,
    pub judgeserver_ip: String,
    pub docker_network_id: Option<String>,
    pub docker_network_name: Option<String>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub event_secret_ciphertext: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub event_secret_nonce: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub flagserver_token_ciphertext: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub flagserver_token_nonce: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub judgeserver_token_ciphertext: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub judgeserver_token_nonce: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub wg_server_private_key_ciphertext: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub wg_server_private_key_nonce: Option<Vec<u8>>,
    pub wg_server_public_key: Option<String>,
    pub key_version: i32,
    pub free_reset_count: i32,
    pub extra_reset_penalty: i64,
    pub reset_protection_secs: i32,
    pub judge_max_concurrency: i32,
    pub judge_default_timeout_secs: i32,
    pub judge_retry_interval_secs: i32,
    pub judge_grace_period_secs: i32,
    pub round_duration_secs: i32,
    pub archive_retention_hours: i32,
    pub verified_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub verified_revision: Option<String>,
    pub pause_remaining_secs: Option<i32>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
