//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_judge_batches")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub round_id: Uuid,
    pub total_tasks: i32,
    pub completed_tasks: i32,
    pub failed_tasks: i32,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awd_events::Entity",
        from = "Column::EventId",
        to = "super::awd_events::Column::EventId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdEvents,
    #[sea_orm(has_many = "super::awd_judge_tasks::Entity")]
    AwdJudgeTasks,
    #[sea_orm(
        belongs_to = "super::awd_rounds::Entity",
        from = "Column::RoundId",
        to = "super::awd_rounds::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdRounds,
}

impl Related<super::awd_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEvents.def()
    }
}

impl Related<super::awd_judge_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdJudgeTasks.def()
    }
}

impl Related<super::awd_rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdRounds.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
