//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "awd_flag_issues")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "awd_flag_issues_event_id_round_id_flag_hash_key")]
    pub event_id: Uuid,
    #[sea_orm(unique_key = "awd_flag_issues_event_id_round_id_flag_hash_key")]
    pub round_id: Uuid,
    #[sea_orm(unique_key = "awd_flag_issues_event_id_round_id_gamebox_instance_id_key")]
    pub gamebox_instance_id: Uuid,
    #[sea_orm(unique_key = "awd_flag_issues_event_id_round_id_flag_hash_key")]
    pub flag_hash: String,
    pub issued_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awd_flag_submissions::Entity")]
    AwdFlagSubmissions,
    #[sea_orm(
        belongs_to = "super::awd_gamebox_instances::Entity",
        from = "Column::GameboxInstanceId",
        to = "super::awd_gamebox_instances::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdGameboxInstances,
    #[sea_orm(
        belongs_to = "super::awd_rounds::Entity",
        from = "Column::RoundId",
        to = "super::awd_rounds::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdRounds,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::awd_flag_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagSubmissions.def()
    }
}

impl Related<super::awd_gamebox_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdGameboxInstances.def()
    }
}

impl Related<super::awd_rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdRounds.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
