//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awdp_fix_rounds")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub sequence: i32,
    pub starts_at: DateTimeWithTimeZone,
    pub cutoff_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awdp_evaluations::Entity")]
    AwdpEvaluations,
    #[sea_orm(has_many = "super::awdp_patch_submissions::Entity")]
    AwdpPatchSubmissions,
    #[sea_orm(has_many = "super::awdp_score_events::Entity")]
    AwdpScoreEvents,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::awdp_evaluations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpEvaluations.def()
    }
}

impl Related<super::awdp_patch_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpPatchSubmissions.def()
    }
}

impl Related<super::awdp_score_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpScoreEvents.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
