//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use ipnetwork::IpNetwork;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awdp_event_networks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_id: Uuid,
    #[sea_orm(unique)]
    pub network_name: String,
    #[sea_orm(column_type = "custom(\"cidr\")", unique)]
    pub subnet_cidr: IpNetwork,
    #[sea_orm(column_type = "custom(\"cidr\")")]
    pub dynamic_pool_cidr: IpNetwork,
    #[sea_orm(column_type = "custom(\"inet\")")]
    pub judge_ip: IpNetwork,
    #[sea_orm(column_type = "Text", nullable)]
    pub docker_network_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
