//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::AwdpPhase;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awdp_runs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub event_id: Option<Uuid>,
    pub gamebox_id: Option<Uuid>,
    pub owner_user_id: Option<Uuid>,
    pub owner_team_id: Option<Uuid>,
    pub phase: AwdpPhase,
    pub break_duration_secs: i32,
    pub fix_duration_secs: i32,
    pub fix_round_interval_secs: i32,
    pub break_score: i64,
    pub fix_round_score: i64,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub break_ends_at: Option<DateTimeWithTimeZone>,
    pub fix_started_at: Option<DateTimeWithTimeZone>,
    pub fix_ends_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub current_round: i32,
    pub total_rounds: i32,
    pub next_action_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awdp_breaks::Entity")]
    AwdpBreaks,
    #[sea_orm(has_many = "super::awdp_evaluations::Entity")]
    AwdpEvaluations,
    #[sea_orm(has_many = "super::awdp_fix_rounds::Entity")]
    AwdpFixRounds,
    #[sea_orm(has_many = "super::awdp_instances::Entity")]
    AwdpInstances,
    #[sea_orm(has_many = "super::awdp_patch_submissions::Entity")]
    AwdpPatchSubmissions,
    #[sea_orm(has_many = "super::awdp_score_events::Entity")]
    AwdpScoreEvents,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
    #[sea_orm(
        belongs_to = "super::gameboxes::Entity",
        from = "Column::GameboxId",
        to = "super::gameboxes::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Gameboxes,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::awdp_breaks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpBreaks.def()
    }
}

impl Related<super::awdp_evaluations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpEvaluations.def()
    }
}

impl Related<super::awdp_fix_rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpFixRounds.def()
    }
}

impl Related<super::awdp_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpInstances.def()
    }
}

impl Related<super::awdp_patch_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpPatchSubmissions.def()
    }
}

impl Related<super::awdp_score_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpScoreEvents.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gameboxes.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
