//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::AwdpEvaluationKind;
use super::sea_orm_active_enums::AwdpEvaluationStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awdp_evaluations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub instance_id: Uuid,
    pub fix_round_id: Option<Uuid>,
    pub kind: AwdpEvaluationKind,
    pub status: AwdpEvaluationStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub healthcheck_result: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub judge_result: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exploit_result: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stdout_limited: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stderr_limited: Option<String>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub run_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awdp_fix_rounds::Entity",
        from = "Column::FixRoundId",
        to = "super::awdp_fix_rounds::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdpFixRounds,
    #[sea_orm(
        belongs_to = "super::awdp_runs::Entity",
        from = "Column::RunId",
        to = "super::awdp_runs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdpRuns,
    #[sea_orm(
        belongs_to = "super::event_instances::Entity",
        from = "Column::InstanceId",
        to = "super::event_instances::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventInstances,
}

impl Related<super::awdp_fix_rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpFixRounds.def()
    }
}

impl Related<super::awdp_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpRuns.def()
    }
}

impl Related<super::event_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInstances.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
