//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awdp_score_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub team_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub score_type: String,
    pub fix_round_id: Option<Uuid>,
    pub delta: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub idempotency_key: String,
    pub created_at: DateTimeWithTimeZone,
    pub run_id: Uuid,
    pub gamebox_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awdp_fix_rounds::Entity",
        from = "Column::FixRoundId",
        to = "super::awdp_fix_rounds::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdpFixRounds,
    #[sea_orm(
        belongs_to = "super::awdp_runs::Entity",
        from = "Column::RunId",
        to = "super::awdp_runs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdpRuns,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "(Column::EventId, Column::TeamId)",
        to = "(super::event_teams::Column::EventId, super::event_teams::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams,
    #[sea_orm(
        belongs_to = "super::gameboxes::Entity",
        from = "Column::GameboxId",
        to = "super::gameboxes::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Gameboxes,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::awdp_fix_rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpFixRounds.def()
    }
}

impl Related<super::awdp_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpRuns.def()
    }
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gameboxes.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
