//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awdp_instances")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub instance_id: Uuid,
    pub event_id: Uuid,
    pub event_gamebox_id: Uuid,
    pub owner_user_id: Option<Uuid>,
    pub owner_team_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awdp_event_gameboxes::Entity",
        from = "Column::EventGameboxId",
        to = "super::awdp_event_gameboxes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdpEventGameboxes,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "(Column::EventId, Column::OwnerTeamId)",
        to = "(super::event_teams::Column::EventId, super::event_teams::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
    #[sea_orm(
        belongs_to = "super::instances::Entity",
        from = "Column::InstanceId",
        to = "super::instances::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Instances,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::awdp_event_gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpEventGameboxes.def()
    }
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instances.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
