//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "awdp_patch_submissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Option<Uuid>,
    pub instance_id: Uuid,
    pub fix_round_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub team_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub script_sha256: String,
    #[sea_orm(column_type = "Text")]
    pub script_content: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub submitted_at: DateTimeWithTimeZone,
    pub apply_started_at: Option<DateTimeWithTimeZone>,
    pub applied_at: Option<DateTimeWithTimeZone>,
    pub exit_code: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stdout_limited: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stderr_limited: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub run_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::awdp_fix_rounds::Entity",
        from = "Column::FixRoundId",
        to = "super::awdp_fix_rounds::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AwdpFixRounds,
    #[sea_orm(
        belongs_to = "super::awdp_runs::Entity",
        from = "Column::RunId",
        to = "super::awdp_runs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AwdpRuns,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "(Column::EventId, Column::TeamId)",
        to = "(super::event_teams::Column::EventId, super::event_teams::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams,
    #[sea_orm(
        belongs_to = "super::instances::Entity",
        from = "Column::InstanceId",
        to = "super::instances::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Instances,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::awdp_fix_rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpFixRounds.def()
    }
}

impl Related<super::awdp_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpRuns.def()
    }
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instances.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
