//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "challenge_revisions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub challenge_id: Uuid,
    pub revision_number: i32,
    #[sea_orm(column_type = "Text")]
    pub version: String,
    #[sea_orm(column_type = "Text")]
    pub source_toml: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub spec_json: Json,
    #[sea_orm(column_type = "Text")]
    pub spec_digest: String,
    #[sea_orm(column_type = "Text")]
    pub package_digest: String,
    #[sea_orm(column_type = "Text")]
    pub flag_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub static_flag_value: Option<String>,
    pub container_port: Option<i32>,
    pub recommended_cpu_millis: i64,
    pub recommended_memory_bytes: i64,
    pub recommended_pids_limit: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub attachment_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub attachment_name: Option<String>,
    pub attachment_size: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub attachment_sha256: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub image_ref: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub image_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub image_repo_digest: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub build_status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub build_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenges::Entity",
        from = "Column::ChallengeId",
        to = "super::challenges::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Challenges,
    #[sea_orm(has_many = "super::event_challenges::Entity")]
    EventChallenges,
    #[sea_orm(has_many = "super::instances::Entity")]
    Instances,
}

impl Related<super::challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenges.def()
    }
}

impl Related<super::event_challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventChallenges.def()
    }
}

impl Related<super::instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instances.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
