//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "challenges")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub safe_name: String,
    #[sea_orm(column_type = "Text")]
    pub category: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub hidden: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_toml: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub spec_json: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub spec_digest: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub package_digest: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub flag_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub static_flag_value: Option<String>,
    pub container_port: Option<i32>,
    pub recommended_cpu_millis: i64,
    pub recommended_memory_bytes: i64,
    pub recommended_pids_limit: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub attachment_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub attachment_name: Option<String>,
    pub attachment_size: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub attachment_sha256: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub image_ref: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub image_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub image_repo_digest: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub build_status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub build_error: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::challenge_set_items::Entity")]
    ChallengeSetItems,
    #[sea_orm(has_many = "super::challenge_writeup::Entity")]
    ChallengeWriteup,
    #[sea_orm(has_many = "super::event_challenge_instance::Entity")]
    EventChallengeInstance,
    #[sea_orm(has_many = "super::jeopardy_challenge_solves::Entity")]
    JeopardyChallengeSolves,
    #[sea_orm(has_many = "super::jeopardy_event_challenges::Entity")]
    JeopardyEventChallenges,
}

impl Related<super::challenge_set_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengeSetItems.def()
    }
}

impl Related<super::challenge_writeup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengeWriteup.def()
    }
}

impl Related<super::event_challenge_instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventChallengeInstance.def()
    }
}

impl Related<super::jeopardy_challenge_solves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JeopardyChallengeSolves.def()
    }
}

impl Related<super::jeopardy_event_challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JeopardyEventChallenges.def()
    }
}

impl Related<super::challenge_sets::Entity> for Entity {
    fn to() -> RelationDef {
        super::challenge_set_items::Relation::ChallengeSets.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::challenge_set_items::Relation::Challenges.def().rev())
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        super::jeopardy_event_challenges::Relation::Events.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::jeopardy_event_challenges::Relation::Challenges
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
