//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "event_teams")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "event_teams_event_id_name_key")]
    pub event_id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "event_teams_event_id_name_key")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub points: f64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub banned: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awd_gamebox_instances::Entity")]
    AwdGameboxInstances,
    #[sea_orm(has_many = "super::awd_judge_tasks::Entity")]
    AwdJudgeTasks,
    #[sea_orm(has_many = "super::awd_reset_records::Entity")]
    AwdResetRecords,
    #[sea_orm(has_many = "super::awd_team_bans::Entity")]
    AwdTeamBans,
    #[sea_orm(has_many = "super::awd_team_networks::Entity")]
    AwdTeamNetworks,
    #[sea_orm(has_many = "super::awd_wireguard_peers::Entity")]
    AwdWireguardPeers,
    #[sea_orm(has_many = "super::event_challenge_solves::Entity")]
    EventChallengeSolves,
    #[sea_orm(has_many = "super::event_instances::Entity")]
    EventInstances,
    #[sea_orm(has_many = "super::event_logs::Entity")]
    EventLogs,
    #[sea_orm(has_many = "super::event_team_members::Entity")]
    EventTeamMembers,
    #[sea_orm(has_many = "super::event_writeup::Entity")]
    EventWriteup,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::awd_gamebox_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdGameboxInstances.def()
    }
}

impl Related<super::awd_judge_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdJudgeTasks.def()
    }
}

impl Related<super::awd_reset_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdResetRecords.def()
    }
}

impl Related<super::awd_team_bans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdTeamBans.def()
    }
}

impl Related<super::awd_team_networks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdTeamNetworks.def()
    }
}

impl Related<super::awd_wireguard_peers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdWireguardPeers.def()
    }
}

impl Related<super::event_challenge_solves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventChallengeSolves.def()
    }
}

impl Related<super::event_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInstances.def()
    }
}

impl Related<super::event_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventLogs.def()
    }
}

impl Related<super::event_team_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeamMembers.def()
    }
}

impl Related<super::event_writeup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventWriteup.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
