//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "event_challenge_instance")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub flag: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub challenge_id: Uuid,
    pub user_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub event_id: Uuid,
    pub team_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenges::Entity",
        from = "Column::ChallengeId",
        to = "super::challenges::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Challenges,
    #[sea_orm(
        belongs_to = "super::event_instances::Entity",
        from = "Column::Id",
        to = "super::event_instances::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventInstances,
    #[sea_orm(
        belongs_to = "super::event_teams::Entity",
        from = "(Column::EventId, Column::TeamId)",
        to = "(super::event_teams::Column::EventId, super::event_teams::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventTeams,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenges.def()
    }
}

impl Related<super::event_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInstances.def()
    }
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
