//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::EventType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub r#type: EventType,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub hidden: bool,
    pub start_time: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub rules: String,
    pub allow_join: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub flag_prefix: Option<String>,
    pub end_time: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awd_event_gameboxes::Entity")]
    AwdEventGameboxes,
    #[sea_orm(has_one = "super::awd_event_networks::Entity")]
    AwdEventNetworks,
    #[sea_orm(has_one = "super::awd_events::Entity")]
    AwdEvents,
    #[sea_orm(has_many = "super::awd_flag_issues::Entity")]
    AwdFlagIssues,
    #[sea_orm(has_many = "super::awd_flag_submissions::Entity")]
    AwdFlagSubmissions,
    #[sea_orm(has_many = "super::awd_gamebox_instances::Entity")]
    AwdGameboxInstances,
    #[sea_orm(has_many = "super::awd_internal_token_rotations::Entity")]
    AwdInternalTokenRotations,
    #[sea_orm(has_many = "super::awd_judge_batches::Entity")]
    AwdJudgeBatches,
    #[sea_orm(has_many = "super::awd_judge_tasks::Entity")]
    AwdJudgeTasks,
    #[sea_orm(has_many = "super::awd_network_allocations::Entity")]
    AwdNetworkAllocations,
    #[sea_orm(has_many = "super::awd_orphan_resources::Entity")]
    AwdOrphanResources,
    #[sea_orm(has_many = "super::awd_precheck_runs::Entity")]
    AwdPrecheckRuns,
    #[sea_orm(has_many = "super::awd_reset_records::Entity")]
    AwdResetRecords,
    #[sea_orm(has_many = "super::awd_rounds::Entity")]
    AwdRounds,
    #[sea_orm(has_many = "super::awd_runtime_resources::Entity")]
    AwdRuntimeResources,
    #[sea_orm(has_many = "super::awd_score_events::Entity")]
    AwdScoreEvents,
    #[sea_orm(has_many = "super::awd_team_bans::Entity")]
    AwdTeamBans,
    #[sea_orm(has_many = "super::awd_team_networks::Entity")]
    AwdTeamNetworks,
    #[sea_orm(has_many = "super::awd_wireguard_peers::Entity")]
    AwdWireguardPeers,
    #[sea_orm(has_many = "super::challenge_solves::Entity")]
    ChallengeSolves,
    #[sea_orm(has_many = "super::event_announcements::Entity")]
    EventAnnouncements,
    #[sea_orm(has_many = "super::event_challenge_solves::Entity")]
    EventChallengeSolves,
    #[sea_orm(has_many = "super::event_challenges::Entity")]
    EventChallenges,
    #[sea_orm(has_many = "super::event_instances::Entity")]
    EventInstances,
    #[sea_orm(has_many = "super::event_logs::Entity")]
    EventLogs,
    #[sea_orm(has_many = "super::event_team_members::Entity")]
    EventTeamMembers,
    #[sea_orm(has_many = "super::event_teams::Entity")]
    EventTeams,
    #[sea_orm(has_many = "super::event_users::Entity")]
    EventUsers,
    #[sea_orm(has_many = "super::event_writeup::Entity")]
    EventWriteup,
}

impl Related<super::awd_event_gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEventGameboxes.def()
    }
}

impl Related<super::awd_event_networks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEventNetworks.def()
    }
}

impl Related<super::awd_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEvents.def()
    }
}

impl Related<super::awd_flag_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagIssues.def()
    }
}

impl Related<super::awd_flag_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagSubmissions.def()
    }
}

impl Related<super::awd_gamebox_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdGameboxInstances.def()
    }
}

impl Related<super::awd_internal_token_rotations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdInternalTokenRotations.def()
    }
}

impl Related<super::awd_judge_batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdJudgeBatches.def()
    }
}

impl Related<super::awd_judge_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdJudgeTasks.def()
    }
}

impl Related<super::awd_network_allocations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdNetworkAllocations.def()
    }
}

impl Related<super::awd_orphan_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdOrphanResources.def()
    }
}

impl Related<super::awd_precheck_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdPrecheckRuns.def()
    }
}

impl Related<super::awd_reset_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdResetRecords.def()
    }
}

impl Related<super::awd_rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdRounds.def()
    }
}

impl Related<super::awd_runtime_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdRuntimeResources.def()
    }
}

impl Related<super::awd_score_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdScoreEvents.def()
    }
}

impl Related<super::awd_team_bans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdTeamBans.def()
    }
}

impl Related<super::awd_team_networks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdTeamNetworks.def()
    }
}

impl Related<super::awd_wireguard_peers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdWireguardPeers.def()
    }
}

impl Related<super::challenge_solves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengeSolves.def()
    }
}

impl Related<super::event_announcements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAnnouncements.def()
    }
}

impl Related<super::event_challenge_solves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventChallengeSolves.def()
    }
}

impl Related<super::event_challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventChallenges.def()
    }
}

impl Related<super::event_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInstances.def()
    }
}

impl Related<super::event_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventLogs.def()
    }
}

impl Related<super::event_team_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeamMembers.def()
    }
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::event_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventUsers.def()
    }
}

impl Related<super::event_writeup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventWriteup.def()
    }
}

impl Related<super::challenges::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_challenges::Relation::Challenges.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_challenges::Relation::Events.def().rev())
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_users::Relation::Events.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
