//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::EventFamily;
use super::sea_orm_active_enums::EventPurpose;
use super::sea_orm_active_enums::ParticipantMode;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub hidden: bool,
    pub start_time: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub rules: String,
    pub allow_join: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub flag_prefix: Option<String>,
    pub end_time: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub family: EventFamily,
    pub purpose: EventPurpose,
    pub participant_mode: ParticipantMode,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub system_key: Option<String>,
    pub is_virtual: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::awd_events::Entity")]
    AwdEvents,
    #[sea_orm(has_many = "super::awd_network_allocations::Entity")]
    AwdNetworkAllocations,
    #[sea_orm(has_many = "super::awdp_event_gameboxes::Entity")]
    AwdpEventGameboxes,
    #[sea_orm(has_one = "super::awdp_events::Entity")]
    AwdpEvents,
    #[sea_orm(has_one = "super::awdp_runs::Entity")]
    AwdpRuns,
    #[sea_orm(has_many = "super::event_announcements::Entity")]
    EventAnnouncements,
    #[sea_orm(has_many = "super::event_challenge_instance::Entity")]
    EventChallengeInstance,
    #[sea_orm(has_many = "super::event_instances::Entity")]
    EventInstances,
    #[sea_orm(has_many = "super::event_logs::Entity")]
    EventLogs,
    #[sea_orm(has_many = "super::event_team_members::Entity")]
    EventTeamMembers,
    #[sea_orm(has_many = "super::event_teams::Entity")]
    EventTeams,
    #[sea_orm(has_many = "super::event_users::Entity")]
    EventUsers,
    #[sea_orm(has_many = "super::event_writeup::Entity")]
    EventWriteup,
    #[sea_orm(has_many = "super::jeopardy_challenge_solves::Entity")]
    JeopardyChallengeSolves,
    #[sea_orm(has_many = "super::jeopardy_event_challenges::Entity")]
    JeopardyEventChallenges,
}

impl Related<super::awd_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEvents.def()
    }
}

impl Related<super::awd_network_allocations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdNetworkAllocations.def()
    }
}

impl Related<super::awdp_event_gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpEventGameboxes.def()
    }
}

impl Related<super::awdp_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpEvents.def()
    }
}

impl Related<super::awdp_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpRuns.def()
    }
}

impl Related<super::event_announcements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAnnouncements.def()
    }
}

impl Related<super::event_challenge_instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventChallengeInstance.def()
    }
}

impl Related<super::event_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInstances.def()
    }
}

impl Related<super::event_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventLogs.def()
    }
}

impl Related<super::event_team_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeamMembers.def()
    }
}

impl Related<super::event_teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeams.def()
    }
}

impl Related<super::event_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventUsers.def()
    }
}

impl Related<super::event_writeup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventWriteup.def()
    }
}

impl Related<super::jeopardy_challenge_solves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JeopardyChallengeSolves.def()
    }
}

impl Related<super::jeopardy_event_challenges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JeopardyEventChallenges.def()
    }
}

impl Related<super::challenges::Entity> for Entity {
    fn to() -> RelationDef {
        super::jeopardy_event_challenges::Relation::Challenges.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::jeopardy_event_challenges::Relation::Events
                .def()
                .rev(),
        )
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_users::Relation::Events.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
