//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "gamebox_revisions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub gamebox_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub version: String,
    pub revision_number: i32,
    #[sea_orm(column_type = "Text")]
    pub source_toml: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub spec_json: Json,
    #[sea_orm(column_type = "Text")]
    pub spec_digest: String,
    #[sea_orm(column_type = "Text")]
    pub package_digest: String,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub image_ref: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub image_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub image_repo_digest: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub username: String,
    pub recommended_cpu_millis: i64,
    pub recommended_memory_bytes: i64,
    pub recommended_pids_limit: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub healthchecks_json: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub judge_script_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub judge_script_content: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub judge_args_json: Option<Json>,
    pub judge_timeout_secs: Option<i32>,
    pub judge_retry_interval_secs: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub build_status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub build_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awd_event_gameboxes::Entity")]
    AwdEventGameboxes,
    #[sea_orm(
        belongs_to = "super::gameboxes::Entity",
        from = "Column::GameboxId",
        to = "super::gameboxes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Gameboxes,
}

impl Related<super::awd_event_gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEventGameboxes.def()
    }
}

impl Related<super::gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gameboxes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
