//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "gameboxes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub safe_name: String,
    #[sea_orm(column_type = "Text")]
    pub category: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub hidden: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awd_event_gameboxes::Entity")]
    AwdEventGameboxes,
    #[sea_orm(has_many = "super::gamebox_revisions::Entity")]
    GameboxRevisions,
}

impl Related<super::awd_event_gameboxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdEventGameboxes.def()
    }
}

impl Related<super::gamebox_revisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameboxRevisions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
