//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "instances")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub owner_user_id: Option<Uuid>,
    pub owner_team_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub image_ref: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub container_id: Option<String>,
    #[sea_orm(column_type = "Text", unique)]
    pub container_name: String,
    #[sea_orm(column_type = "Text")]
    pub runtime_state: String,
    pub runtime_generation: i64,
    pub created_at: DateTimeWithTimeZone,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub stopped_at: Option<DateTimeWithTimeZone>,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::instance_endpoints::Entity")]
    InstanceEndpoints,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::instance_endpoints::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InstanceEndpoints.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
