//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "instance_endpoints")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub instance_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub protocol: String,
    pub container_port: i32,
    #[sea_orm(column_type = "Text")]
    pub public_host: String,
    pub public_port: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event_instances::Entity",
        from = "Column::InstanceId",
        to = "super::event_instances::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventInstances,
}

impl Related<super::event_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInstances.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
