//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "scheduled_tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub group_id: Option<Uuid>,
    pub task_key: String,
    pub trigger_type: String,
    pub status: String,
    pub cron_expr: Option<String>,
    pub execute_at: Option<DateTimeWithTimeZone>,
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub payload: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_msg: Option<String>,
    pub last_run_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub task_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub enabled: bool,
    pub protected: bool,
    pub attempt_count: i32,
    pub max_attempts: i32,
    pub timeout_secs: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub locked_at: Option<DateTimeWithTimeZone>,
    pub heartbeat_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
