//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "awd_event_status")]
#[serde(rename_all = "snake_case")]
pub enum AwdEventStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "configuring")]
    Configuring,
    #[sea_orm(string_value = "deploying")]
    Deploying,
    #[sea_orm(string_value = "deployed")]
    Deployed,
    #[sea_orm(string_value = "prechecking")]
    Prechecking,
    #[sea_orm(string_value = "verified")]
    Verified,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "paused")]
    Paused,
    #[sea_orm(string_value = "network_error")]
    NetworkError,
    #[sea_orm(string_value = "start_blocked")]
    StartBlocked,
    #[sea_orm(string_value = "finished")]
    Finished,
    #[sea_orm(string_value = "archived")]
    Archived,
    #[sea_orm(string_value = "deploy_failed")]
    DeployFailed,
    #[sea_orm(string_value = "verification_failed")]
    VerificationFailed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "awd_network_allocation_kind"
)]
#[serde(rename_all = "snake_case")]
pub enum AwdNetworkAllocationKind {
    #[sea_orm(string_value = "gamebox")]
    Gamebox,
    #[sea_orm(string_value = "wireguard")]
    Wireguard,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "awd_network_allocation_mode"
)]
#[serde(rename_all = "snake_case")]
pub enum AwdNetworkAllocationMode {
    #[sea_orm(string_value = "automatic")]
    Automatic,
    #[sea_orm(string_value = "manual")]
    Manual,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "awd_phase")]
#[serde(rename_all = "snake_case")]
pub enum AwdPhase {
    #[sea_orm(string_value = "hardening")]
    Hardening,
    #[sea_orm(string_value = "attack")]
    Attack,
    #[sea_orm(string_value = "pause")]
    Pause,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "awdp_evaluation_kind"
)]
#[serde(rename_all = "snake_case")]
pub enum AwdpEvaluationKind {
    #[sea_orm(string_value = "manual")]
    Manual,
    #[sea_orm(string_value = "official")]
    Official,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "awdp_evaluation_status"
)]
#[serde(rename_all = "snake_case")]
pub enum AwdpEvaluationStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "no_patch")]
    NoPatch,
    #[sea_orm(string_value = "service_down")]
    ServiceDown,
    #[sea_orm(string_value = "functional_broken")]
    FunctionalBroken,
    #[sea_orm(string_value = "vulnerable")]
    Vulnerable,
    #[sea_orm(string_value = "patched")]
    Patched,
    #[sea_orm(string_value = "platform_error")]
    PlatformError,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "awdp_phase")]
#[serde(rename_all = "snake_case")]
pub enum AwdpPhase {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "break")]
    Break,
    #[sea_orm(string_value = "fix")]
    Fix,
    #[sea_orm(string_value = "ended")]
    Ended,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ban_status")]
#[serde(rename_all = "snake_case")]
pub enum BanStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "pending_unban")]
    PendingUnban,
    #[sea_orm(string_value = "unbanned")]
    Unbanned,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_family")]
#[serde(rename_all = "snake_case")]
pub enum EventFamily {
    #[sea_orm(string_value = "jeopardy")]
    Jeopardy,
    #[sea_orm(string_value = "awd")]
    Awd,
    #[sea_orm(string_value = "awdp")]
    Awdp,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_purpose")]
#[serde(rename_all = "snake_case")]
pub enum EventPurpose {
    #[sea_orm(string_value = "practice")]
    Practice,
    #[sea_orm(string_value = "competition")]
    Competition,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "event_team_member_role"
)]
#[serde(rename_all = "snake_case")]
pub enum EventTeamMemberRole {
    #[sea_orm(string_value = "captain")]
    Captain,
    #[sea_orm(string_value = "member")]
    Member,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "gamebox_status")]
#[serde(rename_all = "snake_case")]
pub enum GameboxStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "creating")]
    Creating,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "ready")]
    Ready,
    #[sea_orm(string_value = "resetting")]
    Resetting,
    #[sea_orm(string_value = "missing")]
    Missing,
    #[sea_orm(string_value = "orphan")]
    Orphan,
    #[sea_orm(string_value = "conflict")]
    Conflict,
    #[sea_orm(string_value = "start_failed")]
    StartFailed,
    #[sea_orm(string_value = "reset_failed")]
    ResetFailed,
    #[sea_orm(string_value = "stopped")]
    Stopped,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "judge_task_status")]
#[serde(rename_all = "snake_case")]
pub enum JudgeTaskStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "up")]
    Up,
    #[sea_orm(string_value = "down")]
    Down,
    #[sea_orm(string_value = "judge_error")]
    JudgeError,
    #[sea_orm(string_value = "judge_timeout")]
    JudgeTimeout,
    #[sea_orm(string_value = "skipped_resetting")]
    SkippedResetting,
    #[sea_orm(string_value = "skipped_banned")]
    SkippedBanned,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "participant_mode")]
#[serde(rename_all = "snake_case")]
pub enum ParticipantMode {
    #[sea_orm(string_value = "individual")]
    Individual,
    #[sea_orm(string_value = "team")]
    Team,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "precheck_status")]
#[serde(rename_all = "snake_case")]
pub enum PrecheckStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "passed")]
    Passed,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "error")]
    Error,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "round_status")]
#[serde(rename_all = "snake_case")]
pub enum RoundStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "grace")]
    Grace,
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "paused")]
    Paused,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "score_event_type")]
#[serde(rename_all = "snake_case")]
pub enum ScoreEventType {
    #[sea_orm(string_value = "attack")]
    Attack,
    #[sea_orm(string_value = "victim_loss")]
    VictimLoss,
    #[sea_orm(string_value = "judge_fix")]
    JudgeFix,
    #[sea_orm(string_value = "judge_down")]
    JudgeDown,
    #[sea_orm(string_value = "first_bonus")]
    FirstBonus,
    #[sea_orm(string_value = "reset_penalty")]
    ResetPenalty,
    #[sea_orm(string_value = "adjustment")]
    Adjustment,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "setting_value_type")]
#[serde(rename_all = "snake_case")]
pub enum SettingValueType {
    #[sea_orm(string_value = "string")]
    String,
    #[sea_orm(string_value = "integer")]
    Integer,
    #[sea_orm(string_value = "boolean")]
    Boolean,
    #[sea_orm(string_value = "float")]
    Float,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "wg_peer_status")]
#[serde(rename_all = "snake_case")]
pub enum WgPeerStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "revoked")]
    Revoked,
    #[sea_orm(string_value = "rotating")]
    Rotating,
}
