//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "awd_event_status")]
#[serde(rename_all = "snake_case")]
pub enum AwdEventStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "configuring")]
    Configuring,
    #[sea_orm(string_value = "deploying")]
    Deploying,
    #[sea_orm(string_value = "deployed")]
    Deployed,
    #[sea_orm(string_value = "prechecking")]
    Prechecking,
    #[sea_orm(string_value = "verified")]
    Verified,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "paused")]
    Paused,
    #[sea_orm(string_value = "network_error")]
    NetworkError,
    #[sea_orm(string_value = "start_blocked")]
    StartBlocked,
    #[sea_orm(string_value = "finished")]
    Finished,
    #[sea_orm(string_value = "archived")]
    Archived,
    #[sea_orm(string_value = "deploy_failed")]
    DeployFailed,
    #[sea_orm(string_value = "verification_failed")]
    VerificationFailed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "awd_phase")]
#[serde(rename_all = "snake_case")]
pub enum AwdPhase {
    #[sea_orm(string_value = "hardening")]
    Hardening,
    #[sea_orm(string_value = "attack")]
    Attack,
    #[sea_orm(string_value = "pause")]
    Pause,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ban_status")]
#[serde(rename_all = "snake_case")]
pub enum BanStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "pending_unban")]
    PendingUnban,
    #[sea_orm(string_value = "unbanned")]
    Unbanned,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "event_team_member_role"
)]
#[serde(rename_all = "snake_case")]
pub enum EventTeamMemberRole {
    #[sea_orm(string_value = "captain")]
    Captain,
    #[sea_orm(string_value = "member")]
    Member,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_type")]
#[serde(rename_all = "snake_case")]
pub enum EventType {
    #[sea_orm(string_value = "jeopardy_practice")]
    JeopardyPractice,
    #[sea_orm(string_value = "jeopardy_single")]
    JeopardySingle,
    #[sea_orm(string_value = "jeopardy_team")]
    JeopardyTeam,
    #[sea_orm(string_value = "awd_team")]
    AwdTeam,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "gamebox_status")]
#[serde(rename_all = "snake_case")]
pub enum GameboxStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "creating")]
    Creating,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "ready")]
    Ready,
    #[sea_orm(string_value = "resetting")]
    Resetting,
    #[sea_orm(string_value = "missing")]
    Missing,
    #[sea_orm(string_value = "orphan")]
    Orphan,
    #[sea_orm(string_value = "conflict")]
    Conflict,
    #[sea_orm(string_value = "start_failed")]
    StartFailed,
    #[sea_orm(string_value = "reset_failed")]
    ResetFailed,
    #[sea_orm(string_value = "stopped")]
    Stopped,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "instance_status")]
#[serde(rename_all = "snake_case")]
pub enum InstanceStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "judge_task_status")]
#[serde(rename_all = "snake_case")]
pub enum JudgeTaskStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "up")]
    Up,
    #[sea_orm(string_value = "down")]
    Down,
    #[sea_orm(string_value = "judge_error")]
    JudgeError,
    #[sea_orm(string_value = "judge_timeout")]
    JudgeTimeout,
    #[sea_orm(string_value = "skipped_resetting")]
    SkippedResetting,
    #[sea_orm(string_value = "skipped_banned")]
    SkippedBanned,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "precheck_status")]
#[serde(rename_all = "snake_case")]
pub enum PrecheckStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "passed")]
    Passed,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "error")]
    Error,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "round_status")]
#[serde(rename_all = "snake_case")]
pub enum RoundStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "grace")]
    Grace,
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "paused")]
    Paused,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "score_event_type")]
#[serde(rename_all = "snake_case")]
pub enum ScoreEventType {
    #[sea_orm(string_value = "attack")]
    Attack,
    #[sea_orm(string_value = "victim_loss")]
    VictimLoss,
    #[sea_orm(string_value = "judge_fix")]
    JudgeFix,
    #[sea_orm(string_value = "judge_down")]
    JudgeDown,
    #[sea_orm(string_value = "first_bonus")]
    FirstBonus,
    #[sea_orm(string_value = "reset_penalty")]
    ResetPenalty,
    #[sea_orm(string_value = "adjustment")]
    Adjustment,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "setting_value_type")]
#[serde(rename_all = "snake_case")]
pub enum SettingValueType {
    #[sea_orm(string_value = "string")]
    String,
    #[sea_orm(string_value = "integer")]
    Integer,
    #[sea_orm(string_value = "boolean")]
    Boolean,
    #[sea_orm(string_value = "float")]
    Float,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "wg_peer_status")]
#[serde(rename_all = "snake_case")]
pub enum WgPeerStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "revoked")]
    Revoked,
    #[sea_orm(string_value = "rotating")]
    Rotating,
}
