//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text", unique)]
    pub nickname: String,
    #[sea_orm(column_type = "Text")]
    pub password: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awd_flag_submissions::Entity")]
    AwdFlagSubmissions,
    #[sea_orm(has_many = "super::awd_reset_records::Entity")]
    AwdResetRecords,
    #[sea_orm(has_many = "super::awd_wireguard_peers::Entity")]
    AwdWireguardPeers,
    #[sea_orm(has_many = "super::awdp_breaks::Entity")]
    AwdpBreaks,
    #[sea_orm(has_many = "super::awdp_instances::Entity")]
    AwdpInstances,
    #[sea_orm(has_many = "super::awdp_patch_submissions::Entity")]
    AwdpPatchSubmissions,
    #[sea_orm(has_many = "super::awdp_run_writeups::Entity")]
    AwdpRunWriteups,
    #[sea_orm(has_many = "super::awdp_runs::Entity")]
    AwdpRuns,
    #[sea_orm(has_many = "super::awdp_score_events::Entity")]
    AwdpScoreEvents,
    #[sea_orm(has_many = "super::challenge_writeup::Entity")]
    ChallengeWriteup,
    #[sea_orm(has_many = "super::discussion_comments::Entity")]
    DiscussionComments,
    #[sea_orm(has_many = "super::discussion_likes::Entity")]
    DiscussionLikes,
    #[sea_orm(has_many = "super::discussions::Entity")]
    Discussions,
    #[sea_orm(has_many = "super::event_challenge_instance::Entity")]
    EventChallengeInstance,
    #[sea_orm(has_many = "super::event_instances::Entity")]
    EventInstances,
    #[sea_orm(has_many = "super::event_logs::Entity")]
    EventLogs,
    #[sea_orm(has_many = "super::event_team_members::Entity")]
    EventTeamMembers,
    #[sea_orm(has_many = "super::event_users::Entity")]
    EventUsers,
    #[sea_orm(has_many = "super::event_writeup::Entity")]
    EventWriteup,
    #[sea_orm(has_many = "super::jeopardy_challenge_solves::Entity")]
    JeopardyChallengeSolves,
    #[sea_orm(has_many = "super::logs::Entity")]
    Logs,
}

impl Related<super::awd_flag_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdFlagSubmissions.def()
    }
}

impl Related<super::awd_reset_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdResetRecords.def()
    }
}

impl Related<super::awd_wireguard_peers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdWireguardPeers.def()
    }
}

impl Related<super::awdp_breaks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpBreaks.def()
    }
}

impl Related<super::awdp_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpInstances.def()
    }
}

impl Related<super::awdp_patch_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpPatchSubmissions.def()
    }
}

impl Related<super::awdp_run_writeups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpRunWriteups.def()
    }
}

impl Related<super::awdp_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpRuns.def()
    }
}

impl Related<super::awdp_score_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AwdpScoreEvents.def()
    }
}

impl Related<super::challenge_writeup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChallengeWriteup.def()
    }
}

impl Related<super::discussion_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscussionComments.def()
    }
}

impl Related<super::discussion_likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscussionLikes.def()
    }
}

impl Related<super::discussions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Discussions.def()
    }
}

impl Related<super::event_challenge_instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventChallengeInstance.def()
    }
}

impl Related<super::event_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInstances.def()
    }
}

impl Related<super::event_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventLogs.def()
    }
}

impl Related<super::event_team_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeamMembers.def()
    }
}

impl Related<super::event_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventUsers.def()
    }
}

impl Related<super::event_writeup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventWriteup.def()
    }
}

impl Related<super::jeopardy_challenge_solves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JeopardyChallengeSolves.def()
    }
}

impl Related<super::logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Logs.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_users::Relation::Events.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_users::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
