name = "test_gg"
version = "1.0.0"
author = "your_email"
category = "web"
description = "hello floatctf"
# optional: safe_name = "test_gg"

[gamebox]
username = "floatctf"

[[gamebox.healthchecks]]
type = "http"
port = 80
path = "/"
expected_status = 200

[judge]
script = "judge/check.py"

[gamebox.recommended_resources]
cpu_millis = 1000
memory_bytes = 536870912
pids_limit = 100
