export type ScheduledTasks = {
  id: string;
  group_id?: string;
  task_name: string;
  description?: string;
  task_key: string;
  trigger_type: string;
  status: string;
  enabled: boolean;
  protected: boolean;
  cron_expr?: string;
  execute_at?: string;
  expires_at?: string;
  payload?: string;
  error_msg?: string;
  last_run_at?: string;
  created_at: string;
  updated_at: string;
  attempt_count: number;
  max_attempts: number;
  timeout_secs?: string;
  last_error?: string;
  locked_at?: string;
  heartbeat_at?: string;
};
