export * from "@/api/axios";
import {
	type FloatDockerContainer,
	type ImageInfo,
	type NetworkInfo,
	adminLoginFn,
	announcementAdminApi,
	challengeAdminApi,
	dashboardAdminApi,
	databaseAdminApi,
	discussionAdminApi,
	dockerAdminApi,
	downloadAdminApi,
	eventAdminApi,
	eventAnnouncementAdminApi,
	eventChallengeAdminApi,
	eventLogAdminApi,
	eventTeamAdminApi,
	eventUserAdminApi,
	eventWriteupAdminApi,
	instanceAdminApi,
	logsAdminApi,
	scheduledTaskAdminApi,
	settingAdminApi,
	superAdminApi,
	systemAdminApi,
	userAdminApi,
	weaponsAdminApi,
} from "@/api/admin";

import {
	announcementServiceApi,
	challengeServiceApi,
	discussionServiceApi,
	eventServiceApi,
	instanceServiceApi,
	solveServiceApi,
	submitServiceApi,
	uploadsServiceApi,
	userServiceApi,
	weaponsServiceApi,
} from "@/api/service";
import { awdAdminApi, awdPlayerApi } from "./awd";

export type { FloatDockerContainer, ImageInfo, NetworkInfo };
export { awdAdminApi, awdPlayerApi };

export const adminApi = {
	login: adminLoginFn,
	system: systemAdminApi,
	settings: settingAdminApi,
	announcements: announcementAdminApi,
	challenges: challengeAdminApi,
	discussions: discussionAdminApi,
	users: userAdminApi,
	events: eventAdminApi,
	instances: instanceAdminApi,
	event_challenges: eventChallengeAdminApi,
	event_users: eventUserAdminApi,
	event_announcements: eventAnnouncementAdminApi,
	event_logs: eventLogAdminApi,
	event_writeups: eventWriteupAdminApi,
	event_teams: eventTeamAdminApi,
	database: databaseAdminApi,
	scheduled_tasks: scheduledTaskAdminApi,
	weapons: weaponsAdminApi,
	logs: logsAdminApi,
	download: downloadAdminApi,
	docker: dockerAdminApi,
	dashboard: dashboardAdminApi,
	super_admin: superAdminApi,
	awd: awdAdminApi,
};

export const serviceApi = {
	users: userServiceApi,
	events: eventServiceApi,
	challenges: challengeServiceApi,
	instances: instanceServiceApi,
	submit: submitServiceApi,
	solves: solveServiceApi,
	weapons: weaponsServiceApi,
	announcements: announcementServiceApi,
	discussions: discussionServiceApi,
	uploads: uploadsServiceApi,
	awd: awdPlayerApi,
};
